#!/usr/bin/env bash

. $HOME/bin/utils.sh
begintrap

version=$(now_branch)
is_for=$(echo $version | grep -o "for-")
if [[ ! -z $is_for ]] ;then
    version="v"$(echo $version | sed -E 's@for-@@g')
fi
cd $REPOS/miyagaw61/linux_kernel_tagfiles/$version
global $@
